import * as React from "react"
import Layout from "../components/layout"
import Seo from "../components/seo"
import "../sass/base/_fonts.scss"
import bgPrivacy from "../images/pollo1.png";

const IndexPage = () => (
  <Layout>
    <Seo title="Terms & Conditions" />
    <div className="privacy">
      <div className="bg-privacy">
        <img src={bgPrivacy} alt="Background privacy" title="background privacy" />
      </div>
      <div className="paragraph">
        <h1>TÉRMINOS Y CONDICIONES DE LA ACTIVIDAD
        “ACTIVA TU CÓDIGO E HIDRÁTATE CON GATORADE”
        </h1>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
        <p>La participación en la actividad <strong>“Activa tu código e hidrátate con Gatorade®”</strong> implica la aceptación total e incondicional de los presentes Términos y Condiciones, los cuales resultan definitivos y vinculantes para quienes decidan participar, y cumplan con los requisitos aquí dispuestos (en adelante los “Participantes” o los “Participantes ganadores” cuando aplique).</p>
        <p>En consecuencia, en el momento en que los Participantes cumplan con los requisitos que se disponen por parte de <strong>PEPSI COLA COLOMBIA LTDA.</strong> (en adelante <strong>“PEPSICO”</strong>o el <strong>“ORGANIZADOR”</strong>) para poder participar en la actividad <strong>“Activa tu código e hidrátate con Gatorade ®”</strong>, se entiende que aceptan de manera voluntaria, expresa e irrevocable sujetarse a los presentes Términos y Condiciones.  En caso en que no esté de acuerdo con los Términos y Condiciones aquí establecidos, deberá abstenerse de participar en la presente actividad.</p>
      </div>
    </div>
  </Layout>
)

export default IndexPage
